kvm: configure: use kvm's configure usage for unknown options
Prevent qemu's configure usage to be printed if an invalid option is
passed to it, allowing kvm's configure to trap those errors and print
the usage instead

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -329,7 +329,7 @@ for opt do
   ;;
   --disable-werror) werror="no"
   ;;
-  *) echo "ERROR: unknown option $opt"; show_help="yes"
+  *) echo "ERROR: unknown option $opt"; exit 1
   ;;
   esac
 done
