kvm: merge from trunk
........
  r4061 | avi | 2006-12-11 14:01:33 +0200 (Mon, 11 Dec 2006) | 2 lines

  kvm: web: modify to reflect merge into mainline Linux
........
  r4063 | avi | 2006-12-11 17:52:50 +0200 (Mon, 11 Dec 2006) | 2 lines

  kvm: mmu: use more conventional error handling during init
........
  r4066 | avi | 2006-12-12 10:00:36 +0200 (Tue, 12 Dec 2006) | 2 lines

  kvm: ./configure: error out if gcc 3.x cannot be located
........
  r4068 | avi | 2006-12-12 10:16:50 +0200 (Tue, 12 Dec 2006) | 2 lines

  kvm: prevent loading of amd module on intel hardware, and vice-versa
........
  r4070 | avi | 2006-12-12 12:19:19 +0200 (Tue, 12 Dec 2006) | 2 lines

  kvm: web: document -no-apic
........

diff --git a/kvm/configure b/kvm/configure
--- a/kvm/configure
+++ b/kvm/configure
@@ -48,6 +48,11 @@ while [[ "$1" = -* ]]; do
     esac
 done
 
+if [[ -z "$qemu_cc" ]]; then
+    echo "$0: cannot locate gcc 3.x. please install it or specify with --qemu-cc"
+    exit 1
+fi
+
 libkvm_kerneldir="$kerneldir"
 if (( want_module )); then
     libkvm_kerneldir=$(readlink -f kernel)
